#! /bin/tcsh -f

set project = "/Users/murray/work/M51"

set RESULTS = "$project/fitdata/ulx8_cutoffpl.csv"

if (-e $RESULTS) rm $RESULTS
touch $RESULTS

set DIRS = "$project/scripts/ULX-8_all_dirs.txt"
set alldirs = `cat $DIRS` 
@ numdirs = $#alldirs
    

echo "number of obs IDs: $numdirs"

@ dirnum = 1
while ( $dirnum <= $numdirs )
 
	set dir = $alldirs[${dirnum}]

   	cd $dir

    	echo "================================================="
    	echo "$dir"
    	echo ""
   	echo "-------------------------------------------------"

	echo "query yes" >! cutoffpl.xco
	echo "statistic chi" >> cutoffpl.xco
	echo "cpd /null" >> cutoffpl.xco
	echo "data none" >> cutoffpl.xco
	echo "@fit_tbabscutoffpl.xcm" >> cutoffpl.xco
	echo "fit" >> cutoffpl.xco
	echo "log cutoffpl.log" >> cutoffpl.xco
	echo "err 2.71 2" >> cutoffpl.xco
	echo "err 2.71 4" >> cutoffpl.xco
	echo "err 2.71 5" >> cutoffpl.xco
	echo "show all" >> cutoffpl.xco
	echo "log none" >> cutoffpl.xco
	echo "data 2 none" >> cutoffpl.xco
	echo "addc 3 cflux" >> cutoffpl.xco
	echo "0.5,-1" >> cutoffpl.xco
	echo "8.0,-1" >> cutoffpl.xco
	echo "-12, 0.01" >> cutoffpl.xco
	echo "new 9 1,-1" >> cutoffpl.xco
	echo "fit" >> cutoffpl.xco
	echo "log cutoffpl_flux.log" >> cutoffpl.xco
	echo "err 2.71 6" >> cutoffpl.xco
	echo "show all" >> cutoffpl.xco
	echo "log none" >> cutoffpl.xco
   
	echo "exit" >> cutoffpl.xco	

	if (! -e cutoffpl_flux.log) xspec - cutoffpl.xco	

	set chisq0 = `awk '/Fit statistic : Chi-Squared/ {chisq=$6}; END {print chisq}' cutoffpl.log`
	set dof0 = `awk '/degrees of freedom/ {dof=$7}; END {print dof}' cutoffpl.log`
	set znh0 = `awk '/zTBabs     nH/ {znh=$7}; END {print znh}' cutoffpl.log`
	set znh0_err1 = `awk '/#     2  / {err=$3}; END {print err}' cutoffpl.log`
	set znh0_err2 = `awk '/#     2  / {err=$4}; END {print err}' cutoffpl.log`
	set gamma0 = `awk '/cutoffpl   PhoIndex/ {gam=$6}; END {print gam}' cutoffpl.log`
	set gamma0_err1 = `awk '/#     4  / {err=$3}; END {print err}' cutoffpl.log`
	set gamma0_err2 = `awk '/#     4  / {err=$4}; END {print err}' cutoffpl.log`
	set cut0 = `awk '/cutoffpl   HighECut/ {cut=$7}; END {print cut}' cutoffpl.log`
	set cut0_err1 = `awk '/#     5  / {err=$3}; END {print err}' cutoffpl.log`
	set cut0_err2 = `awk '/#     5  / {err=$4}; END {print err}' cutoffpl.log`
	set flux0 = `awk '/cflux      lg10Flux/ {flux=$7}; END {print flux}' cutoffpl_flux.log`
	set flux0_err1 = `awk '/#     6  / {err=$3}; END {print err}' cutoffpl_flux.log`
	set flux0_err2 = `awk '/#     6  / {err=$4}; END {print err}' cutoffpl_flux.log`

        echo $chisq0 , $dof0 , $znh0 , $znh0_err1 , $znh0_err2 , $gamma0 , $gamma0_err1 , $gamma0_err2 , $cut0 , $cut0_err1 , $cut0_err2 , $flux0 , $flux0_err1 , $flux0_err2>> $RESULTS


	@ dirnum ++
end
